# .github/workflows/deploy.yml
name: Deploy to IIS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v4

      - name: Run deploy script
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          .\deploy.ps1 -ServiceName "UKGInternalApi" `
                       -RepoDir "C:\sites\ukg-internal" `
                       -HealthUrl "http://localhost:9090/api/v1/status"
